Update README.md
ru-ch/faq pull request #23
Opened 2022-10-13 07:24 UTC by cheaharu

Добавлена группа Знакомим Мам и Пап и телеграмм группа Швейцария. Статус свободен.

2022-10-13 07:25 UTC, cheaharu commented
Добавлена группа Знакомим Мам и Пап и телеграмм группа Швейцария. Статус свободен.

2022-10-14 10:32 UTC, beolnix requested changes

2022-10-14 10:32 UTC, beolnix commented on README.md
> +* [Швейцария. Статус свободен](https://t.me/joinchat/RI7ZYnYVm1plMjU0) - Группа для знакомств и обсуждения отношений в Швейцарии и окрестностях. Продолжение Фейсбук проекта
ссылка на чат есть на 50ой строчке этого файла в параграфе чаты телеграмм

2022-10-15 15:54 UTC, antmaxi commented on README.md
> +* [Швейцария. Статус свободен](https://t.me/joinchat/RI7ZYnYVm1plMjU0) - Группа для знакомств и обсуждения отношений в Швейцарии и окрестностях. Продолжение Фейсбук проекта
+

2022-10-15 15:54 UTC, closed without merging